repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-ast
      - id: debug-statements
      - id: detect-private-key
      - id: check-illegal-windows-names
      - id: mixed-line-ending
        args: [--fix=no]
  - repo: local
    hooks:
      - id: delete-temporary-folders
        name: Delete temporary folders
        entry: powershell.exe -NoProfile -ExecutionPolicy Bypass -File delete_temporary_folders.ps1
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]